apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-laravel
spec:
  selector:
    matchLabels:
      run: my-laravel
  replicas: 2
  template:
    metadata:
      labels:
        run: my-laravel
    spec:
      containers:
      - name: my-laravel
        image: bjnandi/laravel-aws-eks-latest:latest
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: my-laravel-svc
 spec:
   selector:
     run: my-laravel
   ports:
     - port: 80
       targetPort: 80
   type: LoadBalancer